### ISSUE TITLE
npm run build error "Lexical error "

### ISSUE THREAD

**Issue by aapidech** [creativetimofficial/light-bootstrap-dashboard-react#53] opened 2019-06-15 04:47 UTC
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:  MacBook Pro
* Operating System: MacOS 10.13.6
* nodejs : 12.4.0

## Failure Logs
I can not run npm run build. there was an error 

> Lexical error on line 1: Unrecognized text.
  Erroneous area:
1: 100% - $sidebar-width
^.........^
![Screen Shot 2019-06-15 at 11 46 29 AM](https://user-images.githubusercontent.com/51317746/59547107-5ad5b500-8f63-11e9-827c-07f61ec8987d.png)

Please include any relevant log snippets or files here.
[2019-06-15T04_24_13_228Z-debug.log](https://github.com/creativetimofficial/light-bootstrap-dashboard-react/files/3292712/2019-06-15T04_24_13_228Z-debug.log)

**Comment by EINazare** [comment] 2019-06-17 06:01
Hello there, @aapidech ,

This is kind of a duplicate of this issue here: https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/50
Also, my response for your issue is found here: https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/50#issuecomment-492533529

In our issue template we have this line `I checked to make sure that this issue has not already been filed`. I can see that you have checked it, please next time take a moment and search through other issues. Thank you.

Best,
Manu

**Closed by EINazare** 2019-06-17 06:01 UTC

**Comment by binaykmr06** [comment] 2019-09-28 13:52
Try instaed **100% - #{$sidebar-width}**
